### ISSUE TITLE
Missing tr1/unordered_map

### ISSUE THREAD

**Issue by hkujy** [olga-perederieieva/TAsK#1]
Hi, 
I am interested in your work. 
After I clone your code, i notice that the file "tr/unordered_map" is missing"

**Comment by olga-perederieieva** [comment]
tr/unordered_map is part of c++ standard library:
http://stackoverflow.com/questions/4511350/c-map-vs-unordered-map-vs-tr1-unordered-map-vs-ext-unordered-map
However, c++11 does not have it anymore:
https://cplusplusmusings.wordpress.com/2013/06/03/whats-up-with-tr1-and-c11-and-libc/
